Fix support for Symfony 5.x
paysera/lib-logging-extra-bundle pull request #10
Opened 2023-04-07 16:28 UTC by borilyordanov

2023-04-11 07:21 UTC, mSprunskas approved these changes

2023-04-11 14:38 UTC, daniel-valchev-paysera requested changes
Please add a changelog entry for the changes.

2023-04-11 14:38 UTC, daniel-valchev-paysera commented on src/Listener/CorrelationIdListener.php
> +        private $correlationIdProvider;
Add a blank line between the constant and the variable.

2023-04-12 07:22 UTC, daniel-valchev-paysera approved these changes

2023-04-13 16:55 UTC, merged